define('EditPageDesignerGroupEdit', ['EditPageDesignerGroupEditResources'],
	function(resources) {
		function createConstructor(context) {

			var Ext = context.Ext;
			var sandbox = context.sandbox;
			var BPMSoft = context.BPMSoft;
			var viewModel;

			function init() {

				var state = sandbox.publish('GetHistoryState');
				var currentHash = state.hash;
				var currentState = state.state || {};
				if (currentState.moduleId === sandbox.id) {
					return;
				}
				sandbox.publish('ReplaceHistoryState', {
					stateObj: {
						moduleId: sandbox.id
					},
					pageTitle: null,
					hash: currentHash.historyState,
					silent: true
				});
			}
			function render(renderTo) {
				var params = {
					name: BPMSoft.generateGUID(),
					HeaderCaption: resources.localizableStrings.HeaderText,
					GroupLabelCaption: null,
					caption: null
				};
				Ext.apply(params, sandbox.publish('GetGroupConfig', null, [sandbox.id]));
				viewModel = createViewModel(params);
				var viewConfig = getViewConfig();
				var view = Ext.create(viewConfig.className || 'BPMSoft.Container', viewConfig);
				view.bind(viewModel);
				view.render(renderTo);
			}

			function getContainerConfig(id, wrapClass) {
				var container = {
					className: 'BPMSoft.Container',
					items: [],
					id: id,
					selectors: {
						wrapEl: '#' + id
					}
				};
				if (!Ext.isEmpty(wrapClass)) {
					container.classes = {
						wrapClassName: wrapClass
					};
				}
				return container;
			}
			function getViewConfig() {
				var viewConfig = getContainerConfig('autoGeneratedContainer');
				var headerConfig = getContainerConfig('header');
				var utilsConfig = getContainerConfig('utils');
				var itemsContainerConfig = getContainerConfig('itemsContainerConfig');
				headerConfig.items = [
					{
						className: 'BPMSoft.Label',
						caption: {
							bindTo: 'HeaderCaption'
						},
						classes: {
							labelClass: ['header-name']
						},
						width: 'auto'
					}
				];
				utilsConfig.items = [{
					className: 'BPMSoft.Container',
					id: 'utils-left',
					selectors: {
						wrapEl: '#utils-left'
					},
					items: [{
						className: 'BPMSoft.Button',
						margin: '0px 10px 0px 0px',
						caption: resources.localizableStrings.SaveButtonText,
						style: BPMSoft.controls.ButtonEnums.style.ORANGE,
						click: {
							bindTo: 'save'
						}
					}, {
						className: 'BPMSoft.Button',
						margin: '0px 10px 0px 0px',
						style: BPMSoft.controls.ButtonEnums.style.DEFAULT,
						caption: resources.localizableStrings.CancelButtonText,
						click: {
							bindTo: 'cancel'
						}
					}]
				}];
				itemsContainerConfig.items = [{
					className: 'BPMSoft.Label',
					caption: resources.localizableStrings.GroupCaption,
					classes: {
						labelClass: ['object-header-name']
					}
				}, {
					className: 'BPMSoft.TextEdit',
					id: 'GroupCaption',
					selectors: {
						wrapEl: '#GroupCaption'

					},
					value: {
						bindTo: 'caption'
					},
					focused: true
				}];
				viewConfig.items = [headerConfig, utilsConfig, itemsContainerConfig];
				return viewConfig;
			}
			function createViewModel(values) {
				return Ext.create('BPMSoft.BaseViewModel', {
						values: values,
						methods: {
							cancel: function() {
								sandbox.publish('BackHistoryState');
							},
							save: function() {
								var result = {
									caption: this.get('caption'),
									name: this.get('name')
								};
								sandbox.publish('GroupEdited', result, [sandbox.id]);
								sandbox.publish('BackHistoryState');
							}
						}
					}
				);
			}
			return Ext.define('StructureExploreModule', {
				init: init,
				render: render
			});
		}
		return createConstructor;
	});
